#!/bin/sh
cat <<EOF >> /etc/opkg/customfeeds.conf
src/gz passwall2 https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall2
src/gz passwall_luci https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall_luci
src/gz passwall_packages https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall_packages
EOF
wget https://dnbiznet.github.io/modem-script/modem-script/xray-core_1.7.2-1_aarch64_cortex-a53.ipk
wget -O passwall.pub https://master.dl.sourceforge.net/project/openwrt-passwall-build/passwall.pub
opkg-key add passwall.pub
opkg update && opkg install --nodeps luci-app-passwall2 xray-core_1.7.2-1_aarch64_cortex-a53.ipk
uci set passwall2.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall2
/etc/init.d/passwall2 enable
/etc/init.d/passwall2 restart
sed -i '/^exit 0/i sleep 5;/etc/init.d/passwall2 restart' /etc/rc.local
